version: '3.8'

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"

    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    ports:
      - "3100:3100"

    command: -config.file=/etc/loki/local-config.yaml

    volumes:
      - loki-storage:/loki
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.8
    container_name: promtail

    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - ../../logs:/logs

    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana
    container_name: grafana

    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage:
  loki-storage:
  prometheus-storage: