server:
  port: 8085

spring:
  application:
    name: media-service

eureka:
  client:
    webclient:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

grpc:
  server:
    port: 9095
    max-inbound-message-size: 10485760 # 10 MB

supabase:
  url: ${SUPABASE_URL}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY}
  bucket: ${SUPABASE_BUCKET:hotel_storage}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name}:${random.uuid}