server:
  port: 8085

spring:
  application:
    name: media-service

eureka:
  client:
    webclient:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

grpc:
  server:
    port: 9095
    max-inbound-message-size: 10485760 # 10 MB

firebase:
  credentials: classpath:key.json
  storage-bucket: hotel-booking-f6cb8.firebasestorage.app
